(() => {
  if (!document.body) return null;
  const cache = window.__jevFast ||= {ids:new WeakMap(), nodes:new Map(), next:1};
  const identity = e => {
    if (!cache.ids.has(e)) cache.ids.set(e,cache.next++);
    const id=cache.ids.get(e); cache.nodes.set(id,e); return id;
  };
  for (const [id,e] of cache.nodes) if (!e.isConnected) cache.nodes.delete(id);
  // Password fields are observable so the agent can log in, but their contents never leave the page:
  // every value below is masked, and the text is supplied locally, never generated by a model.
  const safe = e => !['file','hidden'].includes(e.type);
  const secret = e => e.type === 'password';
  const shown = e => secret(e) ? (e.value ? '(filled)' : '') : e.value;
  const visible = e => !e.closest('[aria-hidden="true"],[inert]') &&
    e.checkVisibility({checkOpacity:true,checkVisibilityCSS:true});
  const name = (e,seen=new Set()) => {
    if (!e || seen.has(e)) return '';
    seen.add(e);
    const referenced=(e.getAttribute('aria-labelledby')||'').split(/\s+/)
      .map(id=>name(document.getElementById(id),seen)).filter(Boolean).join(' ');
    return referenced || e.getAttribute('aria-label') ||
      [...(e.labels||[])].map(l=>name(l,seen)).filter(Boolean).join(' ') ||
      (['button','submit','reset'].includes(e.type) ? e.value : '') || e.getAttribute('alt') ||
      (e.tagName==='INPUT' ? '' : [...e.childNodes].map(n=>n.nodeType===3 ? n.textContent :
        n.nodeType===1 && n.getAttribute('aria-hidden')!=='true' ? name(n,seen) : '').join(' ').trim()) ||
      e.getAttribute('title') || e.getAttribute('placeholder') || '';
  };
  const roles=['button','link','checkbox','radio','switch','tab','menuitem','menuitemradio',
    'option','gridcell','combobox','textbox','searchbox','spinbutton'];
  const selector='a[href],button,input,textarea,select,summary,[contenteditable="true"],'+
    roles.map(role=>'[role="'+role+'"]').join(',');
  const role = e => {
    const explicit=e.getAttribute('role');
    if (roles.includes(explicit)) return explicit;
    if (e.tagName==='BUTTON' || e.tagName==='SUMMARY') return 'button';
    if (e.tagName==='A') return 'link';
    if (e.tagName==='SELECT') return 'combobox';
    if (e.tagName==='TEXTAREA' || e.isContentEditable) return 'textbox';
    if (e.tagName==='INPUT') {
      if (['checkbox','radio'].includes(e.type)) return e.type;
      if (['button','submit','reset','image'].includes(e.type)) return 'button';
      if (e.type==='search') return 'searchbox';
      if (e.type==='number') return 'spinbutton';
      if (['text','email','url','tel','password'].includes(e.type)) return 'textbox';
    }
    return null;
  };
  // Apps that pin their chrome often scroll a container instead of the window. Take the largest visible one
  // that actually overflows, so a page scrolled that way is still scrollable and its scroll still counts.
  cache.findScroller=()=>{
    if (document.documentElement.scrollHeight>innerHeight+2) return null;
    let best=null, area=0;
    for (const e of document.querySelectorAll('body *')) {
      if (e.scrollHeight<=e.clientHeight+2 || !['auto','scroll'].includes(getComputedStyle(e).overflowY)) continue;
      const r=e.getBoundingClientRect(), a=Math.max(0,Math.min(r.bottom,innerHeight)-Math.max(r.top,0))*
        Math.max(0,Math.min(r.right,innerWidth)-Math.max(r.left,0));
      if (a>area && visible(e)) { best=e; area=a; }
    }
    return best;
  };
  cache.scroller=cache.findScroller();
  cache.pageKey=()=>[performance.timeOrigin,location.href,scrollX,scrollY,cache.scroller?.scrollTop||0,
    innerWidth,innerHeight,
    [...document.querySelectorAll('input,textarea,select')].filter(safe)
      .map(e=>[identity(e),shown(e),e.checked,e.selectedIndex,e.disabled,e.readOnly])];
  cache.guard=e=>{
    if (!e?.isConnected || !visible(e)) return null;
    const scope=e.closest('form,dialog,[role="dialog"],article,li,tr,[role="row"]') || e.parentElement;
    return [identity(e),role(e),name(e),shown(e)??null,e.checked??null,e.selectedIndex??null,
      e.readOnly??null,e.matches(':disabled'),e.getAttribute('aria-disabled'),
      e.getAttribute('aria-expanded'),e.getAttribute('aria-checked'),e.getAttribute('aria-selected'),
      e.getAttribute('href'),scope?.innerText?.slice(0,6000)||''];
  };
  // Many apps make a plain <div> clickable with a script handler and no role: a card, a tile, an avatar.
  // The pointer cursor is the only trace it leaves. Take the outermost pointer element that is not
  // already inside a real control, so a card counts once, not once per nested span.
  const pointer=e=>getComputedStyle(e).cursor==='pointer';
  const scripted=new Set(), candidates=[];
  for (const e of document.querySelectorAll('body *')) {
    if (e.matches(selector)) { candidates.push(e); continue; }
    if (e.ownerSVGElement || e.closest(selector) || !pointer(e) ||
        (e.parentElement && pointer(e.parentElement))) continue;
    scripted.add(e); candidates.push(e);
  }
  // A scripted menu often nests its items inside the trigger (a hover dropdown under a nav tab), so they all
  // inherit its pointer and would collapse into it. Items rendered outside the trigger's own box are a
  // separate surface: split that surface into its items, one per child that carries its own text.
  const inside=(a,b)=>a.left>=b.left-1 && a.right<=b.right+1 && a.top>=b.top-1 && a.bottom<=b.bottom+1;
  const texty=e=>(e.innerText||'').trim()!=='';
  const split=e=>{
    const items=[...e.children].filter(k=>visible(k) && texty(k));
    if (items.length>=2) items.forEach(split);
    else if (pointer(e) && !scripted.has(e)) { scripted.add(e); candidates.push(e); }
  };
  for (const root of [...scripted]) {
    const box=root.getBoundingClientRect();
    for (const d of root.querySelectorAll('*')) {
      if (d.ownerSVGElement || d.matches(selector) || !pointer(d) || !visible(d)) continue;
      const parent=d.parentElement;
      if (inside(d.getBoundingClientRect(),box) ||
          (parent!==root && !inside(parent.getBoundingClientRect(),box))) continue;
      split(d);
    }
  }
  const actions=[];
  for (const e of candidates) {
    if (!safe(e) || !visible(e) || e.matches(':disabled') || e.closest('[aria-disabled="true"]')) continue;
    const r=e.getBoundingClientRect(), x=r.x+r.width/2, y=r.y+r.height/2,
      rname=role(e) || (scripted.has(e) ? 'button' : null);
    if (!rname || r.width<=0 || r.height<=0 || x<0 || y<0 || x>=innerWidth || y>=innerHeight) continue;
    if (rname==='gridcell' && e.querySelector('button,[role="button"]')) continue;
    const base={node:identity(e),role:rname,label:(scripted.has(e) ? name(e).slice(0,200) : name(e))||rname,
      rect:{x:r.x,y:r.y,w:r.width,h:r.height}};
    if (secret(e)) base.secret=true;
    for (const key of ['checked','selected','expanded']) {
      const value=e.getAttribute('aria-'+key);
      if (value!==null) base[key]=value;
    }
    if (['checkbox','radio'].includes(e.type)) base.checked=String(e.checked);
    if (e.tagName==='SELECT') {
      for (const o of e.options) if (!o.selected && !o.disabled && !o.closest('optgroup[disabled]'))
        actions.push({...base,kind:'select',value:o.value,
          current_value:[...e.selectedOptions].map(o=>o.label).join(', '),label:base.label+' → '+o.label});
    } else {
      const editable=!e.readOnly && e.getAttribute('aria-readonly')!=='true' &&
        (['textbox','searchbox','spinbutton'].includes(rname) ||
          (rname==='combobox' && ['INPUT','TEXTAREA'].includes(e.tagName)));
      let value=secret(e) ? shown(e) : 'value' in e ? String(e.value) :
        e.isContentEditable || rname==='combobox' ? e.innerText.trim() : '';
      // A select-style combobox (react-select and kin) keeps its typed filter in the <input> and renders the
      // chosen option beside it, so an empty input does not mean an empty field. Report what the control shows.
      if (rname==='combobox' && e.tagName==='INPUT' && !value) {
        for (let up=e.parentElement, i=0; up && i<4 && !value; up=up.parentElement, i++)
          value=(up.innerText||'').trim().slice(0,200);
      }
      actions.push({...base,kind:editable?'fill':'click',value});
      if (editable) actions.push({...base,kind:'click',value,label:'Open '+base.label});
    }
  }
  // An open dialog is what the user is looking at, but it usually sits late in the DOM, behind a page whose
  // text alone can fill the budget. Read open dialogs first, then the rest of the page.
  const dialogs=[...document.querySelectorAll('dialog[open],[role="dialog"],[role="alertdialog"],[aria-modal="true"]')]
    .filter(d=>visible(d) && !d.parentElement?.closest('dialog[open],[role="dialog"],[role="alertdialog"],[aria-modal="true"]'));
  const words=[], range=document.createRange(); let length=0;
  for (const root of [...dialogs, document.body]) {
    const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT); let node;
    while ((node=walker.nextNode()) && length<6000) {
      const value=node.textContent.trim(), parent=node.parentElement;
      if (!value || !parent || parent.closest('script,style,noscript,template') || !visible(parent)) continue;
      if (root===document.body && dialogs.some(d=>d.contains(parent))) continue;
      range.selectNodeContents(node); const r=range.getBoundingClientRect();
      if (r.width>0 && r.height>0 && r.bottom>0 && r.top<innerHeight && r.right>0 && r.left<innerWidth) {
        words.push(value); length+=value.length;
      }
    }
  }
  const text=words.join('\n').slice(0,6000), scroller=cache.scroller;
  const top=scroller ? scroller.scrollTop : scrollY;
  const height=scroller ? scroller.scrollHeight : document.documentElement.scrollHeight;
  const view=scroller ? scroller.clientHeight : innerHeight;
  // A wheel event scrolls whatever scrolls under the pointer, so aim it at the scroller's visible middle.
  const aim=scroller ? (r=>({x:Math.round((Math.max(0,r.left)+Math.min(r.right,innerWidth))/2),
    y:Math.round((Math.max(0,r.top)+Math.min(r.bottom,innerHeight))/2)}))(scroller.getBoundingClientRect()) : {};
  const page_key=cache.pageKey(), guards={};
  for (const a of actions) if (!(a.node in guards)) guards[a.node]=cache.guard(cache.nodes.get(a.node));
  // Compare meaning and identity. Geometry is always resolved and hit-tested just before input.
  const semantics=actions.map(({rect,...action})=>action);
  const marker=[performance.timeOrigin,location.href,scrollX,scrollY,top,innerWidth,innerHeight,
    document.title,text,semantics,page_key[7]];
  const omitted_actions=Math.max(0,actions.length-250);
  actions.splice(250);
  actions.forEach((a,i)=>a.id='e'+(i+1));
  const step=Math.round(Math.min(560,view*0.7));
  if (top+view<height-2) actions.push({id:'scroll_down',kind:'scroll',label:'Scroll down',delta:step,...aim});
  if (top>0) actions.push({id:'scroll_up',kind:'scroll',label:'Scroll up',delta:-step,...aim});
  actions.push({id:'wait',kind:'wait',label:'Wait for the page to update'});
  return {url:location.href,title:document.title,w:innerWidth,h:innerHeight,text,
    scroll:{y:top,height},actions,marker,page_key,guards,omitted_actions};
})()
